package ch.uzh.supersede.feedbacklibrary.stubs;

import android.content.Context;
import android.content.Intent;
import android.text.TextUtils;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.EditText;
import android.widget.LinearLayout;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.ArrayList;
import java.util.List;

import ch.uzh.supersede.feedbacklibrary.R;
import ch.uzh.supersede.feedbacklibrary.activities.AbstractBaseActivity;
import ch.uzh.supersede.feedbacklibrary.activities.FeedbackActivity;
import ch.uzh.supersede.feedbacklibrary.configurations.Configuration;
import ch.uzh.supersede.feedbacklibrary.configurations.ConfigurationItem;
import ch.uzh.supersede.feedbacklibrary.configurations.OrchestratorConfiguration;
import ch.uzh.supersede.feedbacklibrary.configurations.OrchestratorConfigurationItem;
import ch.uzh.supersede.feedbacklibrary.models.Mechanism;
import ch.uzh.supersede.feedbacklibrary.views.AudioMechanismView;
import ch.uzh.supersede.feedbacklibrary.views.CategoryMechanismView;
import ch.uzh.supersede.feedbacklibrary.views.MechanismView;
import ch.uzh.supersede.feedbacklibrary.views.RatingMechanismView;
import ch.uzh.supersede.feedbacklibrary.views.ScreenshotMechanismView;
import ch.uzh.supersede.feedbacklibrary.views.TextMechanismView;

import static ch.uzh.supersede.feedbacklibrary.utils.Constants.FeedbackActivityConstants.DEFAULT_IMAGE_PATH;
import static ch.uzh.supersede.feedbacklibrary.utils.Constants.FeedbackActivityConstants.TAG;

/**
 * Created by Marco on 15.03.2018.
 */

public class OrchestratorStub extends AbstractBaseActivity implements ScreenshotMechanismView.OnImageChangedListener, AudioMechanismView.MultipleAudioMechanismsListener{

    public void get(Context context){
        boolean isPush = false;
        long pullConfigurationId = -1;
        GsonBuilder gsonBuilder = new GsonBuilder();
        gsonBuilder.setLenient();
        Gson gson = gsonBuilder.create();
        OrchestratorConfigurationItem orchestratorConfigurationItem = gson.fromJson(getJsonString(), OrchestratorConfigurationItem.class);
        if (orchestratorConfigurationItem != null) {
            OrchestratorConfiguration orchestratorConfiguration = new OrchestratorConfiguration(orchestratorConfigurationItem, isPush, pullConfigurationId);
            Configuration activeConfiguration = orchestratorConfiguration.getActiveConfiguration();
            List<Mechanism> mechanisms = activeConfiguration.getMechanisms();


            ArrayList<MechanismView> mechanismViews = new ArrayList<>();
            LayoutInflater layoutInflater = LayoutInflater.from(context);
            LinearLayout linearLayout = getView(R.id.supersede_feedbacklibrary_feedback_activity_layout, LinearLayout.class);

            if (linearLayout != null) {
                for (Mechanism mechanism : mechanisms) {
                    if (mechanism != null && mechanism.isActive()) {
                        resolveMechanism(layoutInflater, linearLayout, mechanism, mechanismViews, getIntent().getStringExtra(DEFAULT_IMAGE_PATH));
                    }
                }
                initCopyByEmailLayout(layoutInflater, linearLayout);
                layoutInflater.inflate(R.layout.send_feedback_layout, linearLayout);
            }
        }
    }

    private void resolveMechanism(LayoutInflater layoutInflater, LinearLayout linearLayout, Mechanism mechanism, ArrayList<MechanismView> mechanismViews, String defaultImagePath) {
        MechanismView mechanismView = null;
        View view = null;
        String type = mechanism.getType();
        switch (type) {
            case Mechanism.ATTACHMENT_TYPE:
                break;
            case Mechanism.AUDIO_TYPE:
                mechanismView = new AudioMechanismView(layoutInflater, mechanism, getResources(), this, getApplicationContext());
                view = mechanismView.getEnclosingLayout();
                break;
            case Mechanism.CATEGORY_TYPE:
                mechanismView = new CategoryMechanismView(layoutInflater, mechanism);
                view = mechanismView.getEnclosingLayout();
                break;
            case Mechanism.RATING_TYPE:
                mechanismView = new RatingMechanismView(layoutInflater, mechanism);
                view = mechanismView.getEnclosingLayout();
                break;
            case Mechanism.SCREENSHOT_TYPE:
                mechanismView = new ScreenshotMechanismView(layoutInflater, mechanism, this, mechanismViews.size(), defaultImagePath);
                view = mechanismView.getEnclosingLayout();
                break;
            case Mechanism.TEXT_TYPE:
                mechanismView = new TextMechanismView(layoutInflater, mechanism);
                view = mechanismView.getEnclosingLayout();
                break;
            default:
                Log.wtf(TAG, "Unknown mechanism type '" + type + "'");
                break;
        }

        if (mechanismView != null && view != null) {
            mechanismViews.add(mechanismView);
            linearLayout.addView(view);
        }
    }

    private void initCopyByEmailLayout(LayoutInflater layoutInflater, LinearLayout linearLayout) {
        //Check sharedPreferences on email existing
        /*
        sharedPreferences = getSharedPreferences("FeedbackApp", Context.MODE_PRIVATE);
        savedEmail = sharedPreferences.getString("email", "");

        View view = layoutInflater.inflate(R.layout.send_by_email_layout, null, false);
        linearLayout.addView(view);

        emailEditText = (EditText) view.findViewById(R.id.sbe_email_et);
        if (!TextUtils.isEmpty(savedEmail)) {
            emailEditText.setText(savedEmail);
        }

        getCopyCheckBox = (CheckBox) view.findViewById(R.id.sbe_get_copy_cb);

        getCopyCheckBox.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
                if (b) {
                    emailEditText.setVisibility(View.VISIBLE);
                } else {
                    emailEditText.setVisibility(View.GONE);
                }
            }
        });
        */
    }

    public static String getJsonString(){
        return "{" +
                "\"configurations\":[{" +
                "\"createdAt\":\"2017-11-13T11:41:53.000+0000\"," +
                "\"generalConfiguration\":" +
                "{" +
                "\"createdAt\":\"2018-01-18T15:06:04.000+0000\"," +
                "\"id\":70," +
                "\"parameters\":[{" +
                "\"id\":822.0," +
                "\"key\":\"successDialog\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-18T16:02:00.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":823.0," +
                "\"key\":\"successMessage\"," +
                "\"value\":\"Thank you for your feedback!\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-18T16:03:35.000+0100\"," +
                "\"order\":0.0}]" +
                "}," +
                "\"id\":40," +
                "\"mechanisms\":[{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":76," +
                "\"order\":3," +
                "\"parameters\":[" +
                "{" +
                "\"id\":369.0," +
                "\"key\":\"labelColor\"," +
                "\"value\":\"#353535\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":1.0" +
                "}," +
                "{" +
                "\"id\":370.0," +
                "\"key\":\"textareaFontColor\"," +
                "\"value\":\"#7A7A7A\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:15:44.000+0100\"," +
                "\"order\":2.0" +
                "}," +
                "{" +
                "\"id\":373.0," +
                "\"key\":\"mandatoryReminder\"," +
                "\"value\":\"Please fill in the text field\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:17:00.000+0100\"," +
                "\"order\":3.0" +
                "}," +
                "{" +
                "\"id\":372.0,\"key\":\"fieldTextAlignment\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":4.0},{\"id\":371.0,\"key\":\"fieldWidth\"," +
                "\"value\":\"200.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:17:00.000+0100\"," +
                "\"order\":5.0" +
                "}," +
                "{" +
                "\"id\":374.0," +
                "\"key\":\"fieldBackgroundColor\"," +
                "\"value\":\"#ffffff\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":6.0" +
                "}," +
                "{" +
                "\"id\":375.0," +
                "\"key\":\"fieldFontType\"," +
                "\"value\":\"normal\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":7.0" +
                "}," +
                "{" +
                "\"id\":377.0," +
                "\"key\":\"undoSteps\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":9.0" +
                "}," +
                "{" +
                "\"id\":378.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":10.0" +
                "}," +
                "{" +
                "\"id\":997.0," +
                "\"key\":\"marginBottom\"," +
                "\"value\":\"5\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":10.0},{\"id\":995.0,\"key\":\"marginTop\",\"value\":\"30\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":10.0},{\"id\":379.0,\"key\":\"hint\",\"value\":\"\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":11.0},{\"id\":380.0,\"key\":\"undoEnabled\",\"value\":\"0.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":12.0},{\"id\":381.0,\"key\":\"mandatory\",\"value\":false,\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":13.0},{\"id\":382.0,\"key\":\"title\",\"value\":\"Feedback\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":14.0},{\"id\":383.0,\"key\":\"labelPositioning\",\"value\":\"left\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":15.0},{\"id\":384.0,\"key\":\"label\",\"value\":\"Please describe the problem you have experienced or your idea to improve the Player.\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":16.0},{\"id\":385.0,\"key\":\"fieldFontSize\",\"value\":\"13.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":17.0},{\"id\":386.0,\"key\":\"validationRegex\",\"value\":\".\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":18.0},{\"id\":387.0,\"key\":\"borderColor\",\"value\":\"#C0C0C0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":19.0},{\"id\":388.0,\"key\":\"borderWidth\",\"value\":\"1.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":20.0},{\"id\":389.0,\"key\":\"maxLength\",\"value\":\"1000.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":21.0},{\"id\":390.0,\"key\":\"validateOnSkip\",\"value\":\"1.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":22.0},{\"id\":391.0,\"key\":\"maxLengthVisible\",\"value\":\"1.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":23.0},{\"id\":392.0,\"key\":\"fieldHeight\",\"value\":\"50.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":24.0},{\"id\":673.0,\"key\":\"clearInput\",\"value\":false,\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-12-11T11:36:14.000+0100\",\"updatedAt\":\"2018-01-26T15:14:54.000+0100\",\"order\":25.0}],\"type\":\"TEXT_TYPE\"},{\"active\":false,\"canBeActivated\":false,\"id\":77,\"order\":2,\"parameters\":[{\"id\":393.0,\"key\":\"maxTime\",\"value\":\"30.0\",\"parameters\":[],\"language\":\"en\",\"createdAt\":\"2017-11-13T12:41:53.000+0100\",\"order\":0.0}],\"type\":\"AUDIO_TYPE\"},{\"active\":true,\"canBeActivated\":false,\"id\":78,\"order\":3,\"parameters\":[{\"id\":675.0,\"key\":\"screenshotUrl\",\"value\":\"http://tools.supersede.atos-sports.tv/image/screenshot.jpg\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-12-25T13:41:23.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":731.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T21:17:23.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":394.0," +
                "\"key\":\"defaultPicture\"," +
                "\"value\":\"lastScreenshot\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":395.0," +
                "\"key\":\"title\"," +
                "\"value\":\"You can also add and edit a screenshot\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"SCREENSHOT_TYPE\"" +
                "}," +
                "{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":79," +
                "\"order\":1," +
                "\"parameters\":[{\"id\":396.0," +
                "\"key\":\"defaultRating\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":733.0," +
                "\"key\":\"cssClass\"," +
                "\"value\":\"valid-on-its-own\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T23:26:44.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":397.0," +
                "\"key\":\"maxRating\"," +
                "\"value\":\"5.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":399.0," +
                "\"key\":\"ratingIcon\"," +
                "\"value\":\"star\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":398.0," +
                "\"key\":\"title\"," +
                "\"value\":\"How do you rate the Player overall?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":998.0," +
                "\"key\":\"marginBottom\"," +
                "\"value\":\"5\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":10.0}]," +
                "\"type\":\"RATING_TYPE\"" +
                "}," +
                "{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":80," +
                "\"order\":2," +
                "\"parameters\":[{\"id\":730.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T21:09:43.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":400.0," +
                "\"key\":\"mandatoryReminder\"," +
                "\"value\":\"Please select at least one category\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":401.0," +
                "\"key\":\"options\"," +
                "\"value\":[{\"id\":403.0," +
                "\"key\":\"VIDEO_IS_FREEZING\"," +
                "\"value\":\"Video is freezing\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":993.0," +
                "\"key\":\"BAD_SOUND_QUALITY\"," +
                "\"value\":\"Bad sound quality\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:46:26.000+0100\"," +
                "\"order\":1.0" +
                "}," +
                "{" +
                "\"id\":402.0," +
                "\"key\":\"SLOW_CONNECTION\"," +
                "\"value\":\"Slow connection\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":2.0" +
                "}," +
                "{" +
                "\"id\":994.0," +
                "\"key\":\"PROBLEMS_TO_ENABLE_FLASH\"," +
                "\"value\":\"Problems to enable Flash\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:46:26.000+0100\"," +
                "\"order\":3.0" +
                "}," +
                "{" +
                "\"id\":404.0," +
                "\"key\":\"BUG_CATEGORY\"," +
                "\"value\":\"Bug\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":4.0}]," +
                "\"parameters\":[{\"id\":403.0," +
                "\"key\":\"VIDEO_IS_FREEZING\"," +
                "\"value\":\"Video is freezing\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":993.0," +
                "\"key\":\"BAD_SOUND_QUALITY\"," +
                "\"value\":\"Bad sound quality\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:46:26.000+0100\"," +
                "\"order\":1.0" +
                "}," +
                "{" +
                "\"id\":402.0," +
                "\"key\":\"SLOW_CONNECTION\"," +
                "\"value\":\"Slow connection\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":2.0" +
                "}," +
                "{" +
                "\"id\":994.0," +
                "\"key\":\"PROBLEMS_TO_ENABLE_FLASH\"," +
                "\"value\":\"Problems to enable Flash\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:46:26.000+0100\"," +
                "\"order\":3.0" +
                "}," +
                "{" +
                "\"id\":404.0," +
                "\"key\":\"BUG_CATEGORY\"," +
                "\"value\":\"Bug\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":4.0}]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":408.0," +
                "\"key\":\"multiple\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":410.0," +
                "\"key\":\"title\"," +
                "\"value\":\"Please tell us," +
                " did you experience any of these?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":407.0," +
                "\"key\":\"ownAllowed\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":409.0," +
                "\"key\":\"mandatory\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":993.0," +
                "\"key\":\"BAD_SOUND_QUALITY\"," +
                "\"value\":\"Bad sound quality\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:46:26.000+0100\"," +
                "\"order\":1.0" +
                "}," +
                "{" +
                "\"id\":994.0," +
                "\"key\":\"PROBLEMS_TO_ENABLE_FLASH\"," +
                "\"value\":\"Problems to enable Flash\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:46:26.000+0100\"," +
                "\"order\":3.0}]," +
                "\"type\":\"CATEGORY_TYPE\"" +
                "}," +
                "{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":113," +
                "\"order\":9," +
                "\"parameters\":[{\"id\":672.0," +
                "\"key\":\"borderColor\"," +
                "\"value\":\"#C0C0C0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-12-11T11:33:28.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":671.0," +
                "\"key\":\"fieldHeight\"," +
                "\"value\":\"27.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-12-11T11:31:40.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":670.0," +
                "\"key\":\"label\"," +
                "\"value\":\"Please enter your email address and," +
                " with some luck," +
                " you will win a tablet\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-12-11T11:29:39.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":674.0," +
                "\"key\":\"validateEmail\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-12-11T11:50:30.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"TEXT_TYPE\"" +
                "}," +
                "{" +
                "\"active\":false," +
                "\"canBeActivated\":false," +
                "\"id\":114," +
                "\"order\":0," +
                "\"parameters\":[{\"id\":679.0," +
                "\"key\":\"NO\"," +
                "\"value\":\"No\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:38:16.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":732.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T21:18:16.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":678.0," +
                "\"key\":\"YES\"," +
                "\"value\":\"Yes\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:37:52.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":677.0," +
                "\"key\":\"options\"," +
                "\"value\":[{\"id\":679.0," +
                "\"key\":\"NO\"," +
                "\"value\":\"No\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:38:16.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":678.0," +
                "\"key\":\"YES\"," +
                "\"value\":\"Yes\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:37:52.000+0100\"," +
                "\"order\":0.0}]," +
                "\"parameters\":[{\"id\":679.0," +
                "\"key\":\"NO\"," +
                "\"value\":\"No\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:38:16.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":678.0," +
                "\"key\":\"YES\"," +
                "\"value\":\"Yes\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:37:52.000+0100\"," +
                "\"order\":0.0}]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:37:20.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":680.0," +
                "\"key\":\"multiple\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:38:35.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":676.0," +
                "\"key\":\"title\"," +
                "\"value\":\"Did you enjoy using our application?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-17T20:35:49.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"CATEGORY_TYPE\"" +
                "}," +
                "{" +
                "\"active\":false," +
                "\"canBeActivated\":false," +
                "\"id\":115," +
                "\"order\":6," +
                "\"parameters\":[{\"id\":684.0," +
                "\"key\":\"fieldWidth\"," +
                "\"value\":\"200.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":687.0," +
                "\"key\":\"fieldBackgroundColor\"," +
                "\"value\":\"#ffffff\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":704.0," +
                "\"key\":\"maxLengthVisible\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":698.0," +
                "\"key\":\"fieldFontSize\"," +
                "\"value\":\"13.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":700.0," +
                "\"key\":\"borderColor\"," +
                "\"value\":\"#C0C0C0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":689.0," +
                "\"key\":\"clearInput\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":691.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":686.0," +
                "\"key\":\"mandatoryReminder\"," +
                "\"value\":\"Please fill in the text field\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":693.0," +
                "\"key\":\"undoEnabled\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":705.0," +
                "\"key\":\"fieldHeight\"," +
                "\"value\":\"50.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":688.0," +
                "\"key\":\"fieldFontType\"," +
                "\"value\":\"normal\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":690.0," +
                "\"key\":\"undoSteps\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":697.0," +
                "\"key\":\"label\"," +
                "\"value\":\"Do you think any new feature should be added?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":703.0," +
                "\"key\":\"validateOnSkip\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":695.0," +
                "\"key\":\"title\"," +
                "\"value\":\"Feedback\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":694.0," +
                "\"key\":\"mandatory\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":682.0," +
                "\"key\":\"labelColor\"," +
                "\"value\":\"#353535\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":683.0," +
                "\"key\":\"textareaFontColor\"," +
                "\"value\":\"#7A7A7A\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":685.0," +
                "\"key\":\"fieldTextAlignment\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":696.0," +
                "\"key\":\"labelPositioning\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":701.0," +
                "\"key\":\"borderWidth\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":692.0," +
                "\"key\":\"hint\"," +
                "\"value\":\"\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":699.0," +
                "\"key\":\"validationRegex\"," +
                "\"value\":\".\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":702.0," +
                "\"key\":\"maxLength\"," +
                "\"value\":\"1000.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"TEXT_TYPE\"" +
                "}," +
                "{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":116," +
                "\"order\":8," +
                "\"parameters\":[{\"id\":708.0," +
                "\"key\":\"fieldWidth\"," +
                "\"value\":\"200.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":724.0," +
                "\"key\":\"borderColor\"," +
                "\"value\":\"#C0C0C0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":717.0," +
                "\"key\":\"undoEnabled\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":729.0," +
                "\"key\":\"fieldHeight\"," +
                "\"value\":\"50.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":714.0," +
                "\"key\":\"undoSteps\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":719.0," +
                "\"key\":\"title\"," +
                "\"value\":\"Feedback\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":718.0," +
                "\"key\":\"mandatory\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":725.0," +
                "\"key\":\"borderWidth\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":723.0," +
                "\"key\":\"validationRegex\"," +
                "\"value\":\".\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":711.0," +
                "\"key\":\"fieldBackgroundColor\"," +
                "\"value\":\"#ffffff\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":728.0," +
                "\"key\":\"maxLengthVisible\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":722.0," +
                "\"key\":\"fieldFontSize\"," +
                "\"value\":\"13.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":713.0," +
                "\"key\":\"clearInput\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":715.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":710.0," +
                "\"key\":\"mandatoryReminder\"," +
                "\"value\":\"Please fill in the text field\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":712.0," +
                "\"key\":\"fieldFontType\"," +
                "\"value\":\"normal\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":721.0," +
                "\"key\":\"label\"," +
                "\"value\":\"In case you have further comments," +
                " please let us know\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":727.0," +
                "\"key\":\"validateOnSkip\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":706.0," +
                "\"key\":\"labelColor\"," +
                "\"value\":\"#353535\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":707.0," +
                "\"key\":\"textareaFontColor\"," +
                "\"value\":\"#7A7A7A\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":709.0," +
                "\"key\":\"fieldTextAlignment\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":720.0," +
                "\"key\":\"labelPositioning\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":716.0," +
                "\"key\":\"hint\"," +
                "\"value\":\"\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":726.0," +
                "\"key\":\"maxLength\"," +
                "\"value\":\"1000.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":999.0," +
                "\"key\":\"marginBottom\"," +
                "\"value\":\"15\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":10.0" +
                "}," +
                "{" +
                "\"id\":996.0," +
                "\"key\":\"marginTop\"," +
                "\"value\":\"30\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:14:54.000+0100\"," +
                "\"order\":10.0}]," +
                "\"type\":\"TEXT_TYPE\"}]," +
                "\"type\":\"PUSH\"" +
                "}," +
                "{" +
                "\"createdAt\":\"2018-01-26T12:31:04.000+0000\"," +
                "\"generalConfiguration\":{\"createdAt\":\"2018-01-26T12:31:51.000+0000\"," +
                "\"id\":71," +
                "\"parameters\":[{\"id\":828.0," +
                "\"key\":\"likelihood\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T13:38:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":827.0," +
                "\"key\":\"actionOnlyOncePerPageLoad\"," +
                "\"value\":\"1\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T13:35:29.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":829.0," +
                "\"key\":\"doNotDisturbTimeDuration\"," +
                "\"value\":\"30\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T13:40:49.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":831.0," +
                "\"key\":\"pullDelay\"," +
                "\"value\":\"5\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T14:08:22.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":830.0," +
                "\"key\":\"reviewActive\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T14:02:25.000+0100\"," +
                "\"order\":0.0}]" +
                "}," +
                "\"id\":51," +
                "\"mechanisms\":[{\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":128," +
                "\"order\":2," +
                "\"parameters\":[{\"id\":838.0," +
                "\"key\":\"fieldWidth\"," +
                "\"value\":\"200.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":841.0," +
                "\"key\":\"fieldBackgroundColor\"," +
                "\"value\":\"#ffffff\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":858.0," +
                "\"key\":\"maxLengthVisible\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":852.0," +
                "\"key\":\"fieldFontSize\"," +
                "\"value\":\"13.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":854.0," +
                "\"key\":\"borderColor\"," +
                "\"value\":\"#C0C0C0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":843.0," +
                "\"key\":\"clearInput\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":845.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":840.0," +
                "\"key\":\"mandatoryReminder\"," +
                "\"value\":\"Please fill in the text field\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":847.0," +
                "\"key\":\"undoEnabled\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":859.0," +
                "\"key\":\"fieldHeight\"," +
                "\"value\":\"50.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":842.0," +
                "\"key\":\"fieldFontType\"," +
                "\"value\":\"normal\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":844.0," +
                "\"key\":\"undoSteps\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":851.0," +
                "\"key\":\"label\"," +
                "\"value\":\"Do you think any new feature should be added?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":857.0," +
                "\"key\":\"validateOnSkip\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":849.0," +
                "\"key\":\"title\"," +
                "\"value\":\"Feedback\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":848.0," +
                "\"key\":\"mandatory\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":836.0," +
                "\"key\":\"labelColor\"," +
                "\"value\":\"#353535\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":837.0," +
                "\"key\":\"textareaFontColor\"," +
                "\"value\":\"#7A7A7A\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":839.0," +
                "\"key\":\"fieldTextAlignment\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":850.0," +
                "\"key\":\"labelPositioning\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":855.0," +
                "\"key\":\"borderWidth\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":846.0," +
                "\"key\":\"hint\"," +
                "\"value\":\"\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":853.0," +
                "\"key\":\"validationRegex\"," +
                "\"value\":\".\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":856.0," +
                "\"key\":\"maxLength\"," +
                "\"value\":\"1000.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"TEXT_TYPE\"" +
                "}," +
                "{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":129," +
                "\"order\":1," +
                "\"parameters\":[{\"id\":833.0," +
                "\"key\":\"defaultRating\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":832.0," +
                "\"key\":\"ratingIcon\"," +
                "\"value\":\"star\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":834.0," +
                "\"key\":\"maxRating\"," +
                "\"value\":\"5.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":835.0," +
                "\"key\":\"title\"," +
                "\"value\":\"How do you like the design of the player?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T14:37:22.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"RATING_TYPE\"}]," +
                "\"type\":\"PULL\"" +
                "}," +
                "{" +
                "\"createdAt\":\"2018-01-26T14:21:28.000+0000\"," +
                "\"generalConfiguration\":{\"id\":72," +
                "\"parameters\":[{\"id\":890.0," +
                "\"key\":\"pullSpecificActive\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T15:49:34.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":885.0," +
                "\"key\":\"likelihood\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T13:38:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":889.0," +
                "\"key\":\"pullActive\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T15:43:29.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":898.0," +
                "\"key\":\"dialogCSSClass\"," +
                "\"value\":\"hide-minimize\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T16:54:47.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":884.0," +
                "\"key\":\"actionOnlyOncePerPageLoad\"," +
                "\"value\":\"1\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T13:35:29.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":886.0," +
                "\"key\":\"doNotDisturbTimeDuration\"," +
                "\"value\":\"8640000\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T13:40:49.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":888.0," +
                "\"key\":\"pullDelay\"," +
                "\"value\":\"3\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T14:08:22.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":887.0," +
                "\"key\":\"cancelActive\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T14:02:25.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":891.0," +
                "\"key\":\"successDialog\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T16:36:13.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":892.0," +
                "\"key\":\"successMessage\"," +
                "\"value\":\"Thank you!\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T16:36:32.000+0100\"," +
                "\"order\":0.0}]" +
                "}," +
                "\"id\":52," +
                "\"mechanisms\":[{\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":130," +
                "\"order\":2," +
                "\"parameters\":[{\"id\":862.0," +
                "\"key\":\"fieldWidth\"," +
                "\"value\":\"200.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":865.0," +
                "\"key\":\"fieldBackgroundColor\"," +
                "\"value\":\"#ffffff\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":882.0," +
                "\"key\":\"maxLengthVisible\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":876.0," +
                "\"key\":\"fieldFontSize\"," +
                "\"value\":\"13.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":878.0," +
                "\"key\":\"borderColor\"," +
                "\"value\":\"#C0C0C0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":867.0," +
                "\"key\":\"clearInput\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":869.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":864.0," +
                "\"key\":\"mandatoryReminder\"," +
                "\"value\":\"Please fill in the text field\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":871.0," +
                "\"key\":\"undoEnabled\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":883.0," +
                "\"key\":\"fieldHeight\"," +
                "\"value\":\"50.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":866.0," +
                "\"key\":\"fieldFontType\"," +
                "\"value\":\"normal\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":868.0," +
                "\"key\":\"undoSteps\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":875.0," +
                "\"key\":\"label\"," +
                "\"value\":\"Further comments?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":881.0," +
                "\"key\":\"validateOnSkip\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":873.0," +
                "\"key\":\"title\"," +
                "\"value\":\"Feedback\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":872.0," +
                "\"key\":\"mandatory\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":860.0," +
                "\"key\":\"labelColor\"," +
                "\"value\":\"#353535\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":861.0," +
                "\"key\":\"textareaFontColor\"," +
                "\"value\":\"#7A7A7A\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":863.0," +
                "\"key\":\"fieldTextAlignment\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":874.0," +
                "\"key\":\"labelPositioning\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":879.0," +
                "\"key\":\"borderWidth\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":870.0," +
                "\"key\":\"hint\"," +
                "\"value\":\"\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":877.0," +
                "\"key\":\"validationRegex\"," +
                "\"value\":\".\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":880.0," +
                "\"key\":\"maxLength\"," +
                "\"value\":\"1000.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"TEXT_TYPE\"" +
                "}," +
                "{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":131," +
                "\"order\":1," +
                "\"parameters\":[{\"id\":894.0," +
                "\"key\":\"defaultRating\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":893.0," +
                "\"key\":\"ratingIcon\"," +
                "\"value\":\"star\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":895.0," +
                "\"key\":\"maxRating\"," +
                "\"value\":\"5.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":896.0," +
                "\"key\":\"title\"," +
                "\"value\":\"How do you rate the design of the medals page?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T14:37:22.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":897.0," +
                "\"key\":\"mandatory\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-26T16:40:06.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"RATING_TYPE\"}]," +
                "\"type\":\"PULL\"" +
                "}," +
                "{" +
                "\"createdAt\":\"2018-03-05T10:48:18.000+0000\"," +
                "\"generalConfiguration\":{\"createdAt\":\"2018-03-05T10:48:57.000+0000\"," +
                "\"id\":75," +
                "\"parameters\":[{\"id\":1029.0," +
                "\"key\":\"pages\"," +
                "\"value\":[{\"id\":1030.0," +
                "\"key\":\"sportsPage\"," +
                "\"value\":\"dss/SUPERSEDE/player/flash/OVPWeb.html#/sportView/\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T11:53:32.000+0100\"," +
                "\"order\":0.0}]," +
                "\"parameters\":[{\"id\":1030.0," +
                "\"key\":\"sportsPage\"," +
                "\"value\":\"dss/SUPERSEDE/player/flash/OVPWeb.html#/sportView/\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T11:53:32.000+0100\"," +
                "\"order\":0.0}]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T11:52:40.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1031.0," +
                "\"key\":\"pullSpecificActive\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T11:55:10.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1037.0," +
                "\"key\":\"likelihood\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T12:09:13.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1039.0," +
                "\"key\":\"onlyDisplayOnce\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T13:08:29.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1038.0," +
                "\"key\":\"pullActive\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T12:14:47.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1035.0," +
                "\"key\":\"hashes\"," +
                "\"value\":[{\"id\":1036.0," +
                "\"key\":\"sportViewHash\"," +
                "\"value\":\"sportsView\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T12:03:47.000+0100\"," +
                "\"order\":0.0}]," +
                "\"parameters\":[{\"id\":1036.0," +
                "\"key\":\"sportViewHash\"," +
                "\"value\":\"sportsView\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T12:03:47.000+0100\"," +
                "\"order\":0.0}]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T12:03:26.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1032.0," +
                "\"key\":\"pullDelay\"," +
                "\"value\":\"5\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T11:56:04.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1033.0," +
                "\"key\":\"successDialog\"," +
                "\"value\":true," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T11:56:43.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1034.0," +
                "\"key\":\"successMessage\"," +
                "\"value\":\"Thank you!\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-03-05T11:57:07.000+0100\"," +
                "\"order\":0.0}]" +
                "}," +
                "\"id\":54," +
                "\"mechanisms\":[{\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":143," +
                "\"order\":2," +
                "\"parameters\":[{\"id\":1002.0," +
                "\"key\":\"fieldWidth\"," +
                "\"value\":\"200.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1005.0," +
                "\"key\":\"fieldBackgroundColor\"," +
                "\"value\":\"#ffffff\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1022.0," +
                "\"key\":\"maxLengthVisible\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1016.0," +
                "\"key\":\"fieldFontSize\"," +
                "\"value\":\"13.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1018.0," +
                "\"key\":\"borderColor\"," +
                "\"value\":\"#C0C0C0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1007.0," +
                "\"key\":\"clearInput\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1009.0," +
                "\"key\":\"labelFontSize\"," +
                "\"value\":\"15.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1004.0," +
                "\"key\":\"mandatoryReminder\"," +
                "\"value\":\"Please fill in the text field\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1011.0," +
                "\"key\":\"undoEnabled\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1023.0," +
                "\"key\":\"fieldHeight\"," +
                "\"value\":\"50.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1006.0," +
                "\"key\":\"fieldFontType\"," +
                "\"value\":\"normal\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1008.0," +
                "\"key\":\"undoSteps\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1015.0," +
                "\"key\":\"label\"," +
                "\"value\":\"How can we improve the sports overview page?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1021.0," +
                "\"key\":\"validateOnSkip\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1013.0," +
                "\"key\":\"title\"," +
                "\"value\":\"Feedback\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1012.0," +
                "\"key\":\"mandatory\"," +
                "\"value\":false," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1000.0," +
                "\"key\":\"labelColor\"," +
                "\"value\":\"#353535\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1001.0," +
                "\"key\":\"textareaFontColor\"," +
                "\"value\":\"#7A7A7A\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1003.0," +
                "\"key\":\"fieldTextAlignment\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1014.0," +
                "\"key\":\"labelPositioning\"," +
                "\"value\":\"left\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1019.0," +
                "\"key\":\"borderWidth\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1010.0," +
                "\"key\":\"hint\"," +
                "\"value\":\"\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1017.0," +
                "\"key\":\"validationRegex\"," +
                "\"value\":\".\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1020.0," +
                "\"key\":\"maxLength\"," +
                "\"value\":\"1000.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"TEXT_TYPE\"" +
                "}," +
                "{" +
                "\"active\":true," +
                "\"canBeActivated\":false," +
                "\"id\":144," +
                "\"order\":1," +
                "\"parameters\":[{\"id\":1024.0," +
                "\"key\":\"defaultRating\"," +
                "\"value\":\"0.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-27T15:44:09.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1025.0," +
                "\"key\":\"cssClass\"," +
                "\"value\":\"valid-on-its-own\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-27T15:44:09.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1026.0," +
                "\"key\":\"ratingIcon\"," +
                "\"value\":\"star\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-27T15:44:09.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1027.0," +
                "\"key\":\"maxRating\"," +
                "\"value\":\"5.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-27T15:44:09.000+0100\"," +
                "\"order\":0.0" +
                "}," +
                "{" +
                "\"id\":1028.0," +
                "\"key\":\"title\"," +
                "\"value\":\"How do you rate the sports overview page?\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2018-01-27T15:44:09.000+0100\"," +
                "\"order\":0.0}]," +
                "\"type\":\"RATING_TYPE\"}]," +
                "\"type\":\"PULL\"}]," +
                "\"createdAt\":\"2017-11-13T11:41:53.000+0000\"," +
                "\"generalConfiguration\":{\"createdAt\":\"2017-11-13T11:41:53.000+0000\"," +
                "\"id\":50," +
                "\"parameters\":[{\"id\":368.0," +
                "\"key\":\"reviewActive\"," +
                "\"value\":\"1.0\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:12:43.000+0100\"," +
                "\"order\":1.0" +
                "}," +
                "{" +
                "\"id\":367.0," +
                "\"key\":\"mainColor\"," +
                "\"value\":\"#00ff00\"," +
                "\"parameters\":[]," +
                "\"language\":\"en\"," +
                "\"createdAt\":\"2017-11-13T12:41:53.000+0100\"," +
                "\"updatedAt\":\"2018-01-26T15:12:43.000+0100\"," +
                "\"order\":2.0}]" +
                "}," +
                "\"id\":14," +
                "\"name\":\"ATOS Test Application\"," +
                "\"state\":1" +
                "}";
    }

    public static OrchestratorConfiguration generate(){
        boolean isPush = false;
        long configurationId = 22;
        long state = 1;

        List<ConfigurationItem> configurationItemList = new ArrayList<>();
        ConfigurationItem configurationItem = new ConfigurationItem();
        //TODO: Set Attributes
        configurationItem.setMechanismConfigurationItems(null);
        configurationItemList.add(configurationItem);
        OrchestratorConfigurationItem orchestratorConfigurationItem = new OrchestratorConfigurationItem();
        orchestratorConfigurationItem.setConfigurationItems(configurationItemList);
        //TODO: Set Attributes
        orchestratorConfigurationItem.setCreatedAt(null);
        orchestratorConfigurationItem.setGeneralConfigurationItem(null);
        orchestratorConfigurationItem.setId(configurationId);
        orchestratorConfigurationItem.setName(null);
        orchestratorConfigurationItem.setState(state);
        OrchestratorConfiguration orchestratorConfiguration = new OrchestratorConfiguration(orchestratorConfigurationItem,isPush,configurationId);
        return orchestratorConfiguration;
    }

    @Override
    public void onImageAnnotate(ScreenshotMechanismView screenshotMechanismView) {

    }

    @Override
    public void onImageSelect(ScreenshotMechanismView screenshotMechanismView) {

    }

    @Override
    public void onImageClick(ScreenshotMechanismView screenshotMechanismView) {

    }

    @Override
    public void onRecordStart(long audioMechanismId) {

    }

    @Override
    public void onRecordStop() {

    }
}
