/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jmotger' at '30/06/16 9:47' with Gradle 2.13
 *
 * @author jmotger, @date 30/06/16 9:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
